# Site settings
title: Lei Pinji
email: leipinji@gmail.com
description: Pinji's personal blog for collection of bioinformatics data analysis methods, biological scientific thoughts, advanced technologies in cancer therapies.
#baseurl: "" 
url: "http://leipinji.github.io" # the base hostname & protocol for your site
twitter_username: LeiLei_Pinji
github_username: leipinji

# Build settings
markdown: kramdown
